# 1) Import Libraries

In [1]:
# Initial configs
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style="whitegrid")

# 2) Load Dataset

In [2]:
df = pd.read_csv(r"..\data\dataset.csv")

In [3]:
df.head()

,subject,age,sex,test_time,motor_updrs,total_updrs,jitter,jitter_abs,jitter_rap,jitter_ppq5,...,shimmer_db,shimmer_apq3,shimmer_apq5,shimmer_apq11,shimmer_dda,nhr,hnr,rpde,dfa,ppe
0,1,72,False,5.6431,28.199,34.398,0.00662,0.000034,0.00401,0.00317,...,0.230,0.01438,0.01309,0.01662,0.04314,0.014290,21.640,0.41888,0.54842,0.16006
1,1,72,False,12.6660,28.447,34.894,0.00300,0.000017,0.00132,0.00150,...,0.179,0.00994,0.01072,0.01689,0.02982,0.011112,27.183,0.43493,0.56477,0.10810
2,1,72,False,19.6810,28.695,35.389,0.00481,0.000025,0.00205,0.00208,...,0.181,0.00734,0.00844,0.01458,0.02202,0.020220,23.047,0.46222,0.54405,0.21014
3,1,72,False,25.6470,28.905,35.810,0.00528,0.000027,0.00191,0.00264,...,0.327,0.01106,0.01265,0.01963,0.03317,0.027837,24.445,0.48730,0.57794,0.33277
4,1,72,False,33.6420,29.187,36.375,0.00335,0.000020,0.00093,0.00130,...,0.176,0.00679,0.00929,0.01819,0.02036,0.011625,26.126,0.47188,0.56122,0.19361

# 3) Remove Unnecessary Columns

In [4]:
# Column for subject identity, not useful for our ML
# We will use the motor_updrs, so the total will not be useful
df = df.drop(columns=["subject", "total_updrs"])
df.head()

,age,sex,test_time,motor_updrs,jitter,jitter_abs,jitter_rap,jitter_ppq5,jitter_ddp,shimmer,shimmer_db,shimmer_apq3,shimmer_apq5,shimmer_apq11,shimmer_dda,nhr,hnr,rpde,dfa,ppe
0,72,False,5.6431,28.199,0.00662,0.000034,0.00401,0.00317,0.01204,0.02565,0.230,0.01438,0.01309,0.01662,0.04314,0.014290,21.640,0.41888,0.54842,0.16006
1,72,False,12.6660,28.447,0.00300,0.000017,0.00132,0.00150,0.00395,0.02024,0.179,0.00994,0.01072,0.01689,0.02982,0.011112,27.183,0.43493,0.56477,0.10810
2,72,False,19.6810,28.695,0.00481,0.000025,0.00205,0.00208,0.00616,0.01675,0.181,0.00734,0.00844,0.01458,0.02202,0.020220,23.047,0.46222,0.54405,0.21014
3,72,False,25.6470,28.905,0.00528,0.000027,0.00191,0.00264,0.00573,0.02309,0.327,0.01106,0.01265,0.01963,0.03317,0.027837,24.445,0.48730,0.57794,0.33277
4,72,False,33.6420,29.187,0.00335,0.000020,0.00093,0.00130,0.00278,0.01703,0.176,0.00679,0.00929,0.01819,0.02036,0.011625,26.126,0.47188,0.56122,0.19361

We can run some tests with columns such as test_time, Jitter, and Shimmer, and observe which one the model responds to best.

# 4) Handle Categorical Variables

In [5]:
# Transforming sex in 0/1
df["sex"] = df["sex"].astype(int)

# 5) Define Target

In [6]:
X = df.drop(columns=["motor_updrs"])
y = df['motor_updrs']

print(X.head())
print("----------------------------------------------------------------------")
print(y.head())

   age  sex  test_time   jitter  jitter_abs  jitter_rap  jitter_ppq5  \
0   72    0     5.6431  0.00662    0.000034     0.00401      0.00317
1   72    0    12.6660  0.00300    0.000017     0.00132      0.00150
2   72    0    19.6810  0.00481    0.000025     0.00205      0.00208
3   72    0    25.6470  0.00528    0.000027     0.00191      0.00264
4   72    0    33.6420  0.00335    0.000020     0.00093      0.00130

   jitter_ddp  shimmer  shimmer_db  shimmer_apq3  shimmer_apq5  shimmer_apq11  \
0     0.01204  0.02565       0.230       0.01438       0.01309        0.01662
1     0.00395  0.02024       0.179       0.00994       0.01072        0.01689
2     0.00616  0.01675       0.181       0.00734       0.00844        0.01458
3     0.00573  0.02309       0.327       0.01106       0.01265        0.01963
4     0.00278  0.01703       0.176       0.00679       0.00929        0.01819

   shimmer_dda       nhr     hnr     rpde      dfa      ppe
0      0.04314  0.014290  21.640  0.41888  0.54842  0.16006
1      0.02982  0.011112  27.183  0.43493  0.56477  0.10810
2      0.02202  0.020220  23.047  0.46222  0.54405  0.21014
3      0.03317  0.027837  24.445  0.48730  0.57794  0.33277
4      0.02036  0.011625  26.126  0.47188  0.56122  0.19361
----------------------------------------------------------------------
0    28.199
1    28.447
2    28.695
3    28.905
4    29.187
Name: motor_updrs, dtype: float64

# 6) Feature Selection

Here we need to decide if we will use all of the variables that we have, or if we should use only the principals.

In my case, and using the EDA stage, we can choose the second way and use the variables that make more sense.

In [7]:
# Using correlation, this is the best test (but we can change for shimmer)
X = X[["age", "sex", "jitter", "shimmer_apq11", "hnr", "rpde", "dfa", "ppe"]]

X.head()

   age  sex   jitter  shimmer_apq11     hnr     rpde      dfa      ppe
0   72    0  0.00662        0.01662  21.640  0.41888  0.54842  0.16006
1   72    0  0.00300        0.01689  27.183  0.43493  0.56477  0.10810
2   72    0  0.00481        0.01458  23.047  0.46222  0.54405  0.21014
3   72    0  0.00528        0.01963  24.445  0.48730  0.57794  0.33277
4   72    0  0.00335        0.01819  26.126  0.47188  0.56122  0.19361

# 7) Train/Test Split

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42
)

# 8) Scaler Variables

In [9]:
# Doing the scalar of the variables, because we need all in the same scaler
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

# 9) Save Scaler and train/test

In [10]:
import joblib
import os

os.makedirs("../models", exist_ok=True)

joblib.dump(scaler, r"../models/scaler.pkl")

['../models/scaler.pkl']

In [11]:
import os

os.makedirs("../data/processed_data", exist_ok=True)


pd.DataFrame(X_train_scaled).to_csv(
    "../data/processed_data/X_train.csv",
    index=False
)

pd.DataFrame(X_test_scaled).to_csv(
    "../data/processed_data/X_test.csv",
    index=False
)

pd.DataFrame(y_train).to_csv(
    "../data/processed_data/y_train.csv",
    index=False
)

pd.DataFrame(y_test).to_csv(
    "../data/processed_data/y_test.csv",
    index=False
)

# 10) Conclusion

In this notebook, we did the split of which variables of our dataset we will use, based on the EDA process. Although we separated the separating of train and test and we used StandardScaler to make all of the variables on the same scale.

In the end, I exported the StandardScaler (for future API use) and the train-test data to use in the machine learning notebooks.